package:
  name: pyastroimageview
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
  git_rev:
  #git_url: git@waxwing:/opt/git/Astronomy/Python/Utilities/pyastroimageview.gits
  git_url: git@waxwing:/opt/git/Astronomy/Python/Utilities/pyastroimageview.git

requirements:
  host:
   - python
   - setuptools
  run:
   - python >=3.7, <3.8
   - numpy >=1.15
   - astropy >=3.0.4
   - configobj >=5.0.6
   - pyastrobackend >=0.10.0
   - pyqt >=5.9.2
   - pyqtgraph >=0.10.0

build:
  python: {{ PY_VER }}
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ 'py' + environ.get('CONDA_PY') + environ.get('GIT_DESCRIBE_HASH', '') + '_' + environ.get('GIT_DESCRIBE_NUMBER', '0')}}

about:
  home:
  license:
  license_file:
