# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'general_settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GeneralSettingsDialog(object):
    def setupUi(self, GeneralSettingsDialog):
        GeneralSettingsDialog.setObjectName("GeneralSettingsDialog")
        GeneralSettingsDialog.resize(626, 609)
        self.verticalLayout = QtWidgets.QVBoxLayout(GeneralSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(GeneralSettingsDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(350, 0))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.telescope_description = QtWidgets.QPlainTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.telescope_description.sizePolicy().hasHeightForWidth())
        self.telescope_description.setSizePolicy(sizePolicy)
        self.telescope_description.setMinimumSize(QtCore.QSize(0, 20))
        self.telescope_description.setMaximumSize(QtCore.QSize(16777215, 20))
        self.telescope_description.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.telescope_description.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.telescope_description.setTabChangesFocus(True)
        self.telescope_description.setObjectName("telescope_description")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.telescope_description)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.telescope_aperture = QtWidgets.QSpinBox(self.groupBox)
        self.telescope_aperture.setMinimumSize(QtCore.QSize(50, 0))
        self.telescope_aperture.setMaximum(9999)
        self.telescope_aperture.setObjectName("telescope_aperture")
        self.horizontalLayout.addWidget(self.telescope_aperture)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.telescope_obstruction = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.telescope_obstruction.setMinimumSize(QtCore.QSize(50, 0))
        self.telescope_obstruction.setObjectName("telescope_obstruction")
        self.horizontalLayout_2.addWidget(self.telescope_obstruction)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.telescope_focallen = QtWidgets.QSpinBox(self.groupBox)
        self.telescope_focallen.setMaximum(9999)
        self.telescope_focallen.setObjectName("telescope_focallen")
        self.horizontalLayout_7.addWidget(self.telescope_focallen)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(GeneralSettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(350, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.location_name = QtWidgets.QPlainTextEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.location_name.sizePolicy().hasHeightForWidth())
        self.location_name.setSizePolicy(sizePolicy)
        self.location_name.setMinimumSize(QtCore.QSize(0, 20))
        self.location_name.setMaximumSize(QtCore.QSize(16777215, 20))
        self.location_name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.location_name.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.location_name.setTabChangesFocus(True)
        self.location_name.setObjectName("location_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.location_name)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.location_lat_degrees = QtWidgets.QSpinBox(self.groupBox_2)
        self.location_lat_degrees.setMinimum(-90)
        self.location_lat_degrees.setMaximum(90)
        self.location_lat_degrees.setObjectName("location_lat_degrees")
        self.horizontalLayout_4.addWidget(self.location_lat_degrees)
        self.location_lat_minutes = QtWidgets.QSpinBox(self.groupBox_2)
        self.location_lat_minutes.setMaximum(59)
        self.location_lat_minutes.setObjectName("location_lat_minutes")
        self.horizontalLayout_4.addWidget(self.location_lat_minutes)
        self.location_lat_seconds = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.location_lat_seconds.setDecimals(3)
        self.location_lat_seconds.setMaximum(59.99)
        self.location_lat_seconds.setObjectName("location_lat_seconds")
        self.horizontalLayout_4.addWidget(self.location_lat_seconds)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.location_lon_degrees = QtWidgets.QSpinBox(self.groupBox_2)
        self.location_lon_degrees.setMinimum(-90)
        self.location_lon_degrees.setMaximum(90)
        self.location_lon_degrees.setObjectName("location_lon_degrees")
        self.horizontalLayout_3.addWidget(self.location_lon_degrees)
        self.location_lon_minutes = QtWidgets.QSpinBox(self.groupBox_2)
        self.location_lon_minutes.setMaximum(59)
        self.location_lon_minutes.setObjectName("location_lon_minutes")
        self.horizontalLayout_3.addWidget(self.location_lon_minutes)
        self.location_lon_seconds = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.location_lon_seconds.setDecimals(3)
        self.location_lon_seconds.setMaximum(59.999)
        self.location_lon_seconds.setObjectName("location_lon_seconds")
        self.horizontalLayout_3.addWidget(self.location_lon_seconds)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.observer_notes = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.observer_notes.setMinimumSize(QtCore.QSize(0, 24))
        self.observer_notes.setMaximumSize(QtCore.QSize(16777215, 56))
        self.observer_notes.setTabChangesFocus(True)
        self.observer_notes.setObjectName("observer_notes")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.observer_notes)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.location_altitude = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.location_altitude.setDecimals(1)
        self.location_altitude.setMaximum(10000.0)
        self.location_altitude.setObjectName("location_altitude")
        self.horizontalLayout_6.addWidget(self.location_altitude)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(GeneralSettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(600, 75))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 601, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(6, 0, 6, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.sequence_targetdir = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_targetdir.sizePolicy().hasHeightForWidth())
        self.sequence_targetdir.setSizePolicy(sizePolicy)
        self.sequence_targetdir.setMinimumSize(QtCore.QSize(0, 20))
        self.sequence_targetdir.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sequence_targetdir.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sequence_targetdir.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sequence_targetdir.setTabChangesFocus(True)
        self.sequence_targetdir.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.sequence_targetdir.setReadOnly(True)
        self.sequence_targetdir.setObjectName("sequence_targetdir")
        self.gridLayout.addWidget(self.sequence_targetdir, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 0, 1, 1)
        self.sequence_select_targetdir = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sequence_select_targetdir.setMinimumSize(QtCore.QSize(24, 0))
        self.sequence_select_targetdir.setMaximumSize(QtCore.QSize(24, 16777215))
        self.sequence_select_targetdir.setObjectName("sequence_select_targetdir")
        self.gridLayout.addWidget(self.sequence_select_targetdir, 1, 2, 1, 1)
        self.sequence_elements = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_elements.sizePolicy().hasHeightForWidth())
        self.sequence_elements.setSizePolicy(sizePolicy)
        self.sequence_elements.setMinimumSize(QtCore.QSize(0, 20))
        self.sequence_elements.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sequence_elements.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sequence_elements.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sequence_elements.setTabChangesFocus(True)
        self.sequence_elements.setObjectName("sequence_elements")
        self.gridLayout.addWidget(self.sequence_elements, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 110, 601, 90))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(6, 2, 2, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sequence_phd2_stop_ditherfail = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.sequence_phd2_stop_ditherfail.setObjectName("sequence_phd2_stop_ditherfail")
        self.gridLayout_2.addWidget(self.sequence_phd2_stop_ditherfail, 3, 0, 1, 1)
        self.sequence_phd2_stop_losestar = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.sequence_phd2_stop_losestar.setObjectName("sequence_phd2_stop_losestar")
        self.gridLayout_2.addWidget(self.sequence_phd2_stop_losestar, 2, 0, 1, 1)
        self.sequence_phd2_warn_notconnect = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.sequence_phd2_warn_notconnect.setObjectName("sequence_phd2_warn_notconnect")
        self.gridLayout_2.addWidget(self.sequence_phd2_warn_notconnect, 0, 0, 1, 1)
        self.sequence_phd2_stop_loseguiding = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.sequence_phd2_stop_loseguiding.setObjectName("sequence_phd2_stop_loseguiding")
        self.gridLayout_2.addWidget(self.sequence_phd2_stop_loseguiding, 1, 0, 1, 1)
        self.sequence_warn_coolertemp = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.sequence_warn_coolertemp.setObjectName("sequence_warn_coolertemp")
        self.gridLayout_2.addWidget(self.sequence_warn_coolertemp, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.buttonBox = QtWidgets.QDialogButtonBox(GeneralSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.horizontalLayout_5.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(GeneralSettingsDialog)
        self.buttonBox.accepted.connect(GeneralSettingsDialog.accept)
        self.buttonBox.rejected.connect(GeneralSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(GeneralSettingsDialog)
        GeneralSettingsDialog.setTabOrder(self.telescope_description, self.telescope_aperture)
        GeneralSettingsDialog.setTabOrder(self.telescope_aperture, self.telescope_obstruction)
        GeneralSettingsDialog.setTabOrder(self.telescope_obstruction, self.location_name)
        GeneralSettingsDialog.setTabOrder(self.location_name, self.location_lat_degrees)
        GeneralSettingsDialog.setTabOrder(self.location_lat_degrees, self.location_lat_minutes)
        GeneralSettingsDialog.setTabOrder(self.location_lat_minutes, self.location_lat_seconds)
        GeneralSettingsDialog.setTabOrder(self.location_lat_seconds, self.location_lon_degrees)
        GeneralSettingsDialog.setTabOrder(self.location_lon_degrees, self.location_lon_minutes)
        GeneralSettingsDialog.setTabOrder(self.location_lon_minutes, self.location_lon_seconds)
        GeneralSettingsDialog.setTabOrder(self.location_lon_seconds, self.location_altitude)
        GeneralSettingsDialog.setTabOrder(self.location_altitude, self.observer_notes)

    def retranslateUi(self, GeneralSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        GeneralSettingsDialog.setWindowTitle(_translate("GeneralSettingsDialog", "Dialog"))
        self.groupBox.setTitle(_translate("GeneralSettingsDialog", "Telescope"))
        self.label.setText(_translate("GeneralSettingsDialog", "Description"))
        self.label_2.setText(_translate("GeneralSettingsDialog", "Aperture"))
        self.label_3.setText(_translate("GeneralSettingsDialog", "Obstruction)"))
        self.label_10.setText(_translate("GeneralSettingsDialog", "(mm)"))
        self.label_11.setText(_translate("GeneralSettingsDialog", "(%)"))
        self.label_16.setText(_translate("GeneralSettingsDialog", "Focal Length"))
        self.groupBox_2.setTitle(_translate("GeneralSettingsDialog", "Observer"))
        self.label_4.setText(_translate("GeneralSettingsDialog", "Site Name"))
        self.label_5.setText(_translate("GeneralSettingsDialog", "Latitude"))
        self.label_8.setText(_translate("GeneralSettingsDialog", "(+/-DD:MM:SS)"))
        self.label_6.setText(_translate("GeneralSettingsDialog", "Longitude"))
        self.label_9.setText(_translate("GeneralSettingsDialog", "(+/-DD:MM:SS)"))
        self.label_7.setText(_translate("GeneralSettingsDialog", "Notes"))
        self.label_12.setText(_translate("GeneralSettingsDialog", "Altitude"))
        self.label_13.setText(_translate("GeneralSettingsDialog", "(meters)"))
        self.groupBox_3.setTitle(_translate("GeneralSettingsDialog", "Sequence"))
        self.label_14.setText(_translate("GeneralSettingsDialog", "Default Name Elements"))
        self.label_15.setText(_translate("GeneralSettingsDialog", "Target Dir"))
        self.sequence_select_targetdir.setText(_translate("GeneralSettingsDialog", "..."))
        self.sequence_phd2_stop_ditherfail.setText(_translate("GeneralSettingsDialog", "Stop if dither fails"))
        self.sequence_phd2_stop_losestar.setText(_translate("GeneralSettingsDialog", "Stop if PHD2 loses star"))
        self.sequence_phd2_warn_notconnect.setText(_translate("GeneralSettingsDialog", "Warn if PHD2 not connected and guiding"))
        self.sequence_phd2_stop_loseguiding.setText(_translate("GeneralSettingsDialog", "Stop if PHD2 stops guiding"))
        self.sequence_warn_coolertemp.setText(_translate("GeneralSettingsDialog", "Warn if cooler not at target temperature"))

