# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phd2_settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PHD2ControlUI(object):
    def setupUi(self, PHD2ControlUI):
        PHD2ControlUI.setObjectName("PHD2ControlUI")
        PHD2ControlUI.resize(255, 173)
        self.gridLayout = QtWidgets.QGridLayout(PHD2ControlUI)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(PHD2ControlUI)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.phd2_scale = QtWidgets.QDoubleSpinBox(PHD2ControlUI)
        self.phd2_scale.setDecimals(2)
        self.phd2_scale.setMaximum(99.0)
        self.phd2_scale.setObjectName("phd2_scale")
        self.gridLayout.addWidget(self.phd2_scale, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(PHD2ControlUI)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(PHD2ControlUI)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 2)
        self.phd2_threshold = QtWidgets.QDoubleSpinBox(PHD2ControlUI)
        self.phd2_threshold.setDecimals(2)
        self.phd2_threshold.setMaximum(9.0)
        self.phd2_threshold.setObjectName("phd2_threshold")
        self.gridLayout.addWidget(self.phd2_threshold, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(PHD2ControlUI)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(PHD2ControlUI)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(PHD2ControlUI)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(PHD2ControlUI)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(PHD2ControlUI)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(PHD2ControlUI)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(PHD2ControlUI)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(PHD2ControlUI)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.phd2_status = QtWidgets.QLabel(PHD2ControlUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phd2_status.sizePolicy().hasHeightForWidth())
        self.phd2_status.setSizePolicy(sizePolicy)
        self.phd2_status.setObjectName("phd2_status")
        self.horizontalLayout.addWidget(self.phd2_status)
        self.phd2_connect = QtWidgets.QPushButton(PHD2ControlUI)
        self.phd2_connect.setMinimumSize(QtCore.QSize(64, 0))
        self.phd2_connect.setMaximumSize(QtCore.QSize(64, 16777215))
        self.phd2_connect.setObjectName("phd2_connect")
        self.horizontalLayout.addWidget(self.phd2_connect)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 5)
        self.phd2_starttime = QtWidgets.QDoubleSpinBox(PHD2ControlUI)
        self.phd2_starttime.setDecimals(0)
        self.phd2_starttime.setMaximum(99.0)
        self.phd2_starttime.setObjectName("phd2_starttime")
        self.gridLayout.addWidget(self.phd2_starttime, 3, 2, 1, 1)
        self.phd2_settledtime = QtWidgets.QDoubleSpinBox(PHD2ControlUI)
        self.phd2_settledtime.setDecimals(0)
        self.phd2_settledtime.setMaximum(99.0)
        self.phd2_settledtime.setObjectName("phd2_settledtime")
        self.gridLayout.addWidget(self.phd2_settledtime, 4, 2, 1, 1)
        self.phd2_settletimeout = QtWidgets.QDoubleSpinBox(PHD2ControlUI)
        self.phd2_settletimeout.setDecimals(0)
        self.phd2_settletimeout.setMaximum(99.0)
        self.phd2_settletimeout.setObjectName("phd2_settletimeout")
        self.gridLayout.addWidget(self.phd2_settletimeout, 5, 2, 1, 1)

        self.retranslateUi(PHD2ControlUI)
        QtCore.QMetaObject.connectSlotsByName(PHD2ControlUI)

    def retranslateUi(self, PHD2ControlUI):
        _translate = QtCore.QCoreApplication.translate
        PHD2ControlUI.setWindowTitle(_translate("PHD2ControlUI", "Form"))
        self.label.setText(_translate("PHD2ControlUI", "Dither Scale:"))
        self.label_3.setText(_translate("PHD2ControlUI", "guide pixels"))
        self.label_4.setText(_translate("PHD2ControlUI", "Dither Settle Threshold"))
        self.label_5.setText(_translate("PHD2ControlUI", "guide pixels"))
        self.label_6.setText(_translate("PHD2ControlUI", "Dither Settle Start"))
        self.label_7.setText(_translate("PHD2ControlUI", "seconds"))
        self.label_8.setText(_translate("PHD2ControlUI", "Dither Settled Done"))
        self.label_9.setText(_translate("PHD2ControlUI", "seconds"))
        self.label_10.setText(_translate("PHD2ControlUI", "Dither Settile Timeout"))
        self.label_11.setText(_translate("PHD2ControlUI", "seconds"))
        self.label_2.setText(_translate("PHD2ControlUI", "Status"))
        self.phd2_status.setText(_translate("PHD2ControlUI", "TextLabel"))
        self.phd2_connect.setText(_translate("PHD2ControlUI", "Connect"))

