# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phd2_settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PHD2SettingsDialog(object):
    def setupUi(self, PHD2SettingsDialog):
        PHD2SettingsDialog.setObjectName("PHD2SettingsDialog")
        PHD2SettingsDialog.resize(228, 179)
        self.gridLayout = QtWidgets.QGridLayout(PHD2SettingsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(PHD2SettingsDialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(PHD2SettingsDialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(PHD2SettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 3)
        self.label_9 = QtWidgets.QLabel(PHD2SettingsDialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 2, 1, 1)
        self.phd2_settletimeout = QtWidgets.QDoubleSpinBox(PHD2SettingsDialog)
        self.phd2_settletimeout.setDecimals(0)
        self.phd2_settletimeout.setMaximum(99.0)
        self.phd2_settletimeout.setObjectName("phd2_settletimeout")
        self.gridLayout.addWidget(self.phd2_settletimeout, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(PHD2SettingsDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(PHD2SettingsDialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.phd2_settledtime = QtWidgets.QDoubleSpinBox(PHD2SettingsDialog)
        self.phd2_settledtime.setDecimals(0)
        self.phd2_settledtime.setMaximum(99.0)
        self.phd2_settledtime.setObjectName("phd2_settledtime")
        self.gridLayout.addWidget(self.phd2_settledtime, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(PHD2SettingsDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.phd2_scale = QtWidgets.QDoubleSpinBox(PHD2SettingsDialog)
        self.phd2_scale.setDecimals(2)
        self.phd2_scale.setMaximum(99.0)
        self.phd2_scale.setObjectName("phd2_scale")
        self.gridLayout.addWidget(self.phd2_scale, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(PHD2SettingsDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(PHD2SettingsDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(PHD2SettingsDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.phd2_starttime = QtWidgets.QDoubleSpinBox(PHD2SettingsDialog)
        self.phd2_starttime.setDecimals(0)
        self.phd2_starttime.setMaximum(99.0)
        self.phd2_starttime.setObjectName("phd2_starttime")
        self.gridLayout.addWidget(self.phd2_starttime, 2, 1, 1, 1)
        self.phd2_threshold = QtWidgets.QDoubleSpinBox(PHD2SettingsDialog)
        self.phd2_threshold.setDecimals(2)
        self.phd2_threshold.setMaximum(9.0)
        self.phd2_threshold.setObjectName("phd2_threshold")
        self.gridLayout.addWidget(self.phd2_threshold, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(PHD2SettingsDialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 5, 0, 1, 1)

        self.retranslateUi(PHD2SettingsDialog)
        self.buttonBox.accepted.connect(PHD2SettingsDialog.accept)
        self.buttonBox.rejected.connect(PHD2SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PHD2SettingsDialog)

    def retranslateUi(self, PHD2SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        PHD2SettingsDialog.setWindowTitle(_translate("PHD2SettingsDialog", "Dialog"))
        self.label_11.setText(_translate("PHD2SettingsDialog", "seconds"))
        self.label_10.setText(_translate("PHD2SettingsDialog", "Settile Timeout"))
        self.label_9.setText(_translate("PHD2SettingsDialog", "seconds"))
        self.label.setText(_translate("PHD2SettingsDialog", "Dither Scale"))
        self.label_7.setText(_translate("PHD2SettingsDialog", "seconds"))
        self.label_6.setText(_translate("PHD2SettingsDialog", "Settle Start"))
        self.label_4.setText(_translate("PHD2SettingsDialog", "Settle Threshold"))
        self.label_3.setText(_translate("PHD2SettingsDialog", "guide pixels"))
        self.label_5.setText(_translate("PHD2SettingsDialog", "guide pixels"))
        self.label_8.setText(_translate("PHD2SettingsDialog", "Settled Done"))

