# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyastroimageview_filterwheel_settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_filterwheel_settings_widget(object):
    def setupUi(self, filterwheel_settings_widget):
        filterwheel_settings_widget.setObjectName("filterwheel_settings_widget")
        filterwheel_settings_widget.resize(178, 117)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(filterwheel_settings_widget.sizePolicy().hasHeightForWidth())
        filterwheel_settings_widget.setSizePolicy(sizePolicy)
        filterwheel_settings_widget.setMinimumSize(QtCore.QSize(0, 0))
        filterwheel_settings_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_2 = QtWidgets.QGridLayout(filterwheel_settings_widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.filterwheel_setting_disconnect = QtWidgets.QPushButton(filterwheel_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterwheel_setting_disconnect.sizePolicy().hasHeightForWidth())
        self.filterwheel_setting_disconnect.setSizePolicy(sizePolicy)
        self.filterwheel_setting_disconnect.setMinimumSize(QtCore.QSize(64, 0))
        self.filterwheel_setting_disconnect.setMaximumSize(QtCore.QSize(64, 16777215))
        self.filterwheel_setting_disconnect.setObjectName("filterwheel_setting_disconnect")
        self.gridLayout.addWidget(self.filterwheel_setting_disconnect, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(filterwheel_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(filterwheel_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.filterwheel_setting_position = QtWidgets.QLabel(filterwheel_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterwheel_setting_position.sizePolicy().hasHeightForWidth())
        self.filterwheel_setting_position.setSizePolicy(sizePolicy)
        self.filterwheel_setting_position.setObjectName("filterwheel_setting_position")
        self.gridLayout.addWidget(self.filterwheel_setting_position, 3, 1, 1, 2)
        self.filterwheel_setting_status = QtWidgets.QLabel(filterwheel_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterwheel_setting_status.sizePolicy().hasHeightForWidth())
        self.filterwheel_setting_status.setSizePolicy(sizePolicy)
        self.filterwheel_setting_status.setObjectName("filterwheel_setting_status")
        self.gridLayout.addWidget(self.filterwheel_setting_status, 2, 1, 1, 2)
        self.filterwheel_setting_connect = QtWidgets.QPushButton(filterwheel_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterwheel_setting_connect.sizePolicy().hasHeightForWidth())
        self.filterwheel_setting_connect.setSizePolicy(sizePolicy)
        self.filterwheel_setting_connect.setMinimumSize(QtCore.QSize(64, 0))
        self.filterwheel_setting_connect.setMaximumSize(QtCore.QSize(64, 16777215))
        self.filterwheel_setting_connect.setObjectName("filterwheel_setting_connect")
        self.gridLayout.addWidget(self.filterwheel_setting_connect, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filterwheel_setting_move = QtWidgets.QPushButton(filterwheel_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterwheel_setting_move.sizePolicy().hasHeightForWidth())
        self.filterwheel_setting_move.setSizePolicy(sizePolicy)
        self.filterwheel_setting_move.setMinimumSize(QtCore.QSize(48, 0))
        self.filterwheel_setting_move.setMaximumSize(QtCore.QSize(48, 16777215))
        self.filterwheel_setting_move.setObjectName("filterwheel_setting_move")
        self.horizontalLayout.addWidget(self.filterwheel_setting_move)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(filterwheel_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.filterwheel_setting_filter_combobox = QtWidgets.QComboBox(filterwheel_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterwheel_setting_filter_combobox.sizePolicy().hasHeightForWidth())
        self.filterwheel_setting_filter_combobox.setSizePolicy(sizePolicy)
        self.filterwheel_setting_filter_combobox.setObjectName("filterwheel_setting_filter_combobox")
        self.gridLayout.addWidget(self.filterwheel_setting_filter_combobox, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(filterwheel_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(2, 1, 5, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filterwheel_driver_label = QtWidgets.QLabel(filterwheel_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterwheel_driver_label.sizePolicy().hasHeightForWidth())
        self.filterwheel_driver_label.setSizePolicy(sizePolicy)
        self.filterwheel_driver_label.setObjectName("filterwheel_driver_label")
        self.horizontalLayout_2.addWidget(self.filterwheel_driver_label)
        self.filterwheel_setting_setup = QtWidgets.QPushButton(filterwheel_settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterwheel_setting_setup.sizePolicy().hasHeightForWidth())
        self.filterwheel_setting_setup.setSizePolicy(sizePolicy)
        self.filterwheel_setting_setup.setMinimumSize(QtCore.QSize(24, 0))
        self.filterwheel_setting_setup.setMaximumSize(QtCore.QSize(24, 24))
        self.filterwheel_setting_setup.setObjectName("filterwheel_setting_setup")
        self.horizontalLayout_2.addWidget(self.filterwheel_setting_setup)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(filterwheel_settings_widget)
        QtCore.QMetaObject.connectSlotsByName(filterwheel_settings_widget)

    def retranslateUi(self, filterwheel_settings_widget):
        _translate = QtCore.QCoreApplication.translate
        filterwheel_settings_widget.setWindowTitle(_translate("filterwheel_settings_widget", "Form"))
        self.filterwheel_setting_disconnect.setText(_translate("filterwheel_settings_widget", "Disconnect"))
        self.label_2.setText(_translate("filterwheel_settings_widget", "Position"))
        self.label_8.setText(_translate("filterwheel_settings_widget", "Status"))
        self.filterwheel_setting_position.setText(_translate("filterwheel_settings_widget", "TextLabel"))
        self.filterwheel_setting_status.setText(_translate("filterwheel_settings_widget", "TextLabel"))
        self.filterwheel_setting_connect.setText(_translate("filterwheel_settings_widget", "Connect"))
        self.filterwheel_setting_move.setText(_translate("filterwheel_settings_widget", "Move"))
        self.label_7.setText(_translate("filterwheel_settings_widget", "Position"))
        self.label.setText(_translate("filterwheel_settings_widget", " Driver"))
        self.filterwheel_driver_label.setText(_translate("filterwheel_settings_widget", "TextLabel"))
        self.filterwheel_setting_setup.setText(_translate("filterwheel_settings_widget", "..."))

