# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyastroimageview_imagearea_info.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(955, 753)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_tabs = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.image_tabs.sizePolicy().hasHeightForWidth())
        self.image_tabs.setSizePolicy(sizePolicy)
        self.image_tabs.setMinimumSize(QtCore.QSize(0, 0))
        self.image_tabs.setObjectName("image_tabs")
        self.horizontalLayout.addWidget(self.image_tabs)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setVerticalSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.image_size_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_size_label.sizePolicy().hasHeightForWidth())
        self.image_size_label.setSizePolicy(sizePolicy)
        self.image_size_label.setMinimumSize(QtCore.QSize(0, 0))
        self.image_size_label.setText("")
        self.image_size_label.setObjectName("image_size_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.image_size_label)
        self.image_bin_label_label = QtWidgets.QLabel(Form)
        self.image_bin_label_label.setEnabled(True)
        self.image_bin_label_label.setObjectName("image_bin_label_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.image_bin_label_label)
        self.image_bin_label = QtWidgets.QLabel(Form)
        self.image_bin_label.setEnabled(True)
        self.image_bin_label.setText("")
        self.image_bin_label.setObjectName("image_bin_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.image_bin_label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.image_median_label = QtWidgets.QLabel(Form)
        self.image_median_label.setText("")
        self.image_median_label.setObjectName("image_median_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.image_median_label)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.hfr_in_label = QtWidgets.QLabel(Form)
        self.hfr_in_label.setMinimumSize(QtCore.QSize(50, 0))
        self.hfr_in_label.setText("")
        self.hfr_in_label.setObjectName("hfr_in_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.hfr_in_label)
        self.hfr_out = QtWidgets.QLabel(Form)
        self.hfr_out.setObjectName("hfr_out")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.hfr_out)
        self.hfr_out_label = QtWidgets.QLabel(Form)
        self.hfr_out_label.setText("")
        self.hfr_out_label.setObjectName("hfr_out_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.hfr_out_label)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.number_stars_label = QtWidgets.QLabel(Form)
        self.number_stars_label.setMinimumSize(QtCore.QSize(0, 0))
        self.number_stars_label.setText("")
        self.number_stars_label.setObjectName("number_stars_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.number_stars_label)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout)
        self.hfr_histogram_spot = QtWidgets.QHBoxLayout()
        self.hfr_histogram_spot.setSpacing(0)
        self.hfr_histogram_spot.setObjectName("hfr_histogram_spot")
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.hfr_histogram_spot)
        self.pixel_histogram_spot = QtWidgets.QHBoxLayout()
        self.pixel_histogram_spot.setSpacing(0)
        self.pixel_histogram_spot.setObjectName("pixel_histogram_spot")
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.pixel_histogram_spot)
        self.horizontalLayout.addLayout(self.formLayout_2)

        self.retranslateUi(Form)
        self.image_tabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Image Size:"))
        self.image_bin_label_label.setText(_translate("Form", "Image Binning:"))
        self.label_2.setText(_translate("Form", "Median:"))
        self.label_4.setText(_translate("Form", "HFR(in):"))
        self.hfr_out.setText(_translate("Form", "HFR(out):"))
        self.label_5.setText(_translate("Form", "# stars:"))

