# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sequence_settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SequenceSettingsUI(object):
    def setupUi(self, SequenceSettingsUI):
        SequenceSettingsUI.setObjectName("SequenceSettingsUI")
        SequenceSettingsUI.resize(380, 176)
        self.gridLayout = QtWidgets.QGridLayout(SequenceSettingsUI)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(SequenceSettingsUI)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.sequence_name = QtWidgets.QPlainTextEdit(SequenceSettingsUI)
        self.sequence_name.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sequence_name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sequence_name.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sequence_name.setTabChangesFocus(True)
        self.sequence_name.setObjectName("sequence_name")
        self.gridLayout.addWidget(self.sequence_name, 0, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(SequenceSettingsUI)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.sequence_elements = QtWidgets.QPlainTextEdit(SequenceSettingsUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_elements.sizePolicy().hasHeightForWidth())
        self.sequence_elements.setSizePolicy(sizePolicy)
        self.sequence_elements.setMinimumSize(QtCore.QSize(0, 20))
        self.sequence_elements.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sequence_elements.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sequence_elements.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sequence_elements.setTabChangesFocus(True)
        self.sequence_elements.setObjectName("sequence_elements")
        self.gridLayout.addWidget(self.sequence_elements, 1, 1, 1, 2)
        self.sequence_elements_help = QtWidgets.QPushButton(SequenceSettingsUI)
        self.sequence_elements_help.setMinimumSize(QtCore.QSize(25, 0))
        self.sequence_elements_help.setMaximumSize(QtCore.QSize(25, 16777215))
        self.sequence_elements_help.setCheckable(True)
        self.sequence_elements_help.setObjectName("sequence_elements_help")
        self.gridLayout.addWidget(self.sequence_elements_help, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(SequenceSettingsUI)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.sequence_preview = QtWidgets.QLabel(SequenceSettingsUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_preview.sizePolicy().hasHeightForWidth())
        self.sequence_preview.setSizePolicy(sizePolicy)
        self.sequence_preview.setMinimumSize(QtCore.QSize(0, 20))
        self.sequence_preview.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sequence_preview.setObjectName("sequence_preview")
        self.gridLayout.addWidget(self.sequence_preview, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(SequenceSettingsUI)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.sequence_start = QtWidgets.QSpinBox(SequenceSettingsUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_start.sizePolicy().hasHeightForWidth())
        self.sequence_start.setSizePolicy(sizePolicy)
        self.sequence_start.setMinimum(1)
        self.sequence_start.setMaximum(999)
        self.sequence_start.setObjectName("sequence_start")
        self.gridLayout.addWidget(self.sequence_start, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(SequenceSettingsUI)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.sequence_number = QtWidgets.QSpinBox(SequenceSettingsUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_number.sizePolicy().hasHeightForWidth())
        self.sequence_number.setSizePolicy(sizePolicy)
        self.sequence_number.setMinimum(1)
        self.sequence_number.setMaximum(999)
        self.sequence_number.setObjectName("sequence_number")
        self.gridLayout.addWidget(self.sequence_number, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(SequenceSettingsUI)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.sequence_frametype = QtWidgets.QComboBox(SequenceSettingsUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_frametype.sizePolicy().hasHeightForWidth())
        self.sequence_frametype.setSizePolicy(sizePolicy)
        self.sequence_frametype.setObjectName("sequence_frametype")
        self.sequence_frametype.addItem("")
        self.sequence_frametype.addItem("")
        self.sequence_frametype.addItem("")
        self.sequence_frametype.addItem("")
        self.gridLayout.addWidget(self.sequence_frametype, 5, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.sequence_start_stop = QtWidgets.QPushButton(SequenceSettingsUI)
        self.sequence_start_stop.setObjectName("sequence_start_stop")
        self.horizontalLayout.addWidget(self.sequence_start_stop)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 2, 1, 1)

        self.retranslateUi(SequenceSettingsUI)
        QtCore.QMetaObject.connectSlotsByName(SequenceSettingsUI)
        SequenceSettingsUI.setTabOrder(self.sequence_name, self.sequence_elements)
        SequenceSettingsUI.setTabOrder(self.sequence_elements, self.sequence_elements_help)
        SequenceSettingsUI.setTabOrder(self.sequence_elements_help, self.sequence_start)
        SequenceSettingsUI.setTabOrder(self.sequence_start, self.sequence_number)
        SequenceSettingsUI.setTabOrder(self.sequence_number, self.sequence_frametype)
        SequenceSettingsUI.setTabOrder(self.sequence_frametype, self.sequence_start_stop)

    def retranslateUi(self, SequenceSettingsUI):
        _translate = QtCore.QCoreApplication.translate
        SequenceSettingsUI.setWindowTitle(_translate("SequenceSettingsUI", "Form"))
        self.label.setText(_translate("SequenceSettingsUI", "Name"))
        self.label_2.setText(_translate("SequenceSettingsUI", "Title Elements"))
        self.sequence_elements_help.setText(_translate("SequenceSettingsUI", "?"))
        self.label_6.setText(_translate("SequenceSettingsUI", "Preview"))
        self.sequence_preview.setText(_translate("SequenceSettingsUI", "TextLabel"))
        self.label_5.setText(_translate("SequenceSettingsUI", "Starting Index"))
        self.label_4.setText(_translate("SequenceSettingsUI", "Number"))
        self.label_3.setText(_translate("SequenceSettingsUI", "Frame Type"))
        self.sequence_frametype.setItemText(0, _translate("SequenceSettingsUI", "Light"))
        self.sequence_frametype.setItemText(1, _translate("SequenceSettingsUI", "Flat"))
        self.sequence_frametype.setItemText(2, _translate("SequenceSettingsUI", "Dark"))
        self.sequence_frametype.setItemText(3, _translate("SequenceSettingsUI", "Bias"))
        self.sequence_start_stop.setText(_translate("SequenceSettingsUI", "Start"))

